name: ImmortalWrt-Release

env:
  TZ: Asia/Shanghai

on:
  push:
    branches:
      - master
  workflow_dispatch:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: '0 18 * * 2,5,6'

jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      BIN_PATH: /home/runner/work/newifi3-d2-openwrt/newifi3-d2-openwrt/immortalwrt/bin

    steps:
      - name: Clone Repository
        uses: actions/checkout@v2

      - name: Build Environment Initialization
        run: |
          sudo apt-get update
          sudo apt-get -qq remove --purge mysql* php* google* firefox ghc azure-cli \
          dotnet* powershell ruby-full zulu* hhvm llvm*

          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /var/lib/docker
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/hostedtoolcache/go /opt/hostedtoolcache/Ruby /opt/hostedtoolcache/node

          sudo apt-get install -qq -y ack antlr3 asciidoc autoconf automake autopoint binutils bison build-essential \
          bzip2 ccache cmake cpio curl device-tree-compiler ecj fastjar flex gawk gettext gcc-multilib g++-multilib \
          git gperf haveged help2man intltool lib32gcc1 libc6-dev-i386 libelf-dev libglib2.0-dev libgmp3-dev libltdl-dev \
          libmpc-dev libmpfr-dev libncurses5-dev libncursesw5 libncursesw5-dev libreadline-dev libssl-dev libtool lrzsz \
          mkisofs msmtp nano ninja-build p7zip p7zip-full patch pkgconf python2.7 python3 python3-pip python3-ply \
          python-docutils qemu-utils re2c rsync scons squashfs-tools subversion swig texinfo uglifyjs upx-ucl unzip \
          vim wget xmlto xxd zlib1g-dev

          sudo apt-get -qq autoremove --purge
          sudo apt-get -qq clean

      - name: Build Immortalwrt
        run: |
          chmod +x build.sh && ./build.sh

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ env.FILE_DATE }}
          files: |
            ${{ env.BIN_PATH }}/targets/ramips/mt7621/immortalwrt-ramips-mt7621-d-team_newifi-d2-squashfs-sysupgrade.bin
            ${{ env.BIN_PATH }}/targets/ramips/mt7621/immortalwrt-ramips-mt7621-d-team_newifi-d2.manifest