name: Release

env:
  TZ: Asia/Shanghai

on:
  push:
    branches:
      - master
  workflow_dispatch:
  schedule:
    # * is a special character in YAML, so you have to quote this string
    - cron: '0 3 * * 5,6'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BIN_PATH: /home/runner/work/newifi3-d2-openwrt/newifi3-d2-openwrt/lede/bin

    steps:
      - name: Clone Repository
        uses: actions/checkout@v3

      - name: Build Environment Initialization
        run: |
          sudo apt-get update
          sudo apt-get -qq remove --purge mysql* php* google* firefox ghc azure-cli \
          dotnet* powershell ruby-full zulu* llvm*

          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /var/lib/docker
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/hostedtoolcache/go /opt/hostedtoolcache/Ruby /opt/hostedtoolcache/node

          sudo apt-get -qq autoremove --purge
          sudo apt-get -qq clean

      - name: Build lede
        run: |
          chmod +x build.sh && ./build.sh

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ env.FILE_DATE }}
          files: |
            ${{ env.BIN_PATH }}/targets/ramips/mt7621/openwrt-ramips-mt7621-d-team_newifi-d2-squashfs-sysupgrade.bin
            ${{ env.BIN_PATH }}/targets/ramips/mt7621/openwrt-ramips-mt7621-d-team_newifi-d2.manifest